#%RAML 1.0
title: orderid

types:
  order:
    properties:
      orderid:
        type: integer
        required: true
      userid: 
        type: integer
      addressid:
        type: string
      discounted:
        type: string
      created:
        type: datetime
      modified:
        type: string
      status:
        type: string  
      amount:
        type: integer