#%RAML 1.0
title: productid

types:
  product:
    properties:
      productid:
        type: integer
        required: true
      categoryid: 
        type: integer
      name:
        type: string
      description:
        type: string
      video_url:
        type: string
      price:
        type: integer