#%RAML 1.0
title: productid

types:
  product:
      example:
          {"productid": 101,
           "categoryid": 19,
           "name": "kk G-707 Gaming mouse",
           "description": "the G-707 gaming mouse is a razor-sharp mouse",
           "video_url": "https://www.youtube.com/",
           "price": 890
            }