#%RAML 1.0
title: userid

types:
  userid:
    type: object
    properties:
      email: 
       type: string
      username: 
       type: string     
    example:
             {"email": "string",
              "username": "string"}
              