#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/d9e51b3b-43df-4bb4-8b50-ed32a23bce06/ # 
title: user

types:
  user:      
    example:
            [{"email": "test@gmail.com",
              "username": "test"},
              {"email": "test1@gmail.com",
              "username": "test1"} 
             ]         

               